font:
  normal:
    family: SFMono Nerd Font
    style: Regular
  bold:
    family: SFMono Nerd Font
    style: Bold
  italic:
    family: SFMono Nerd Font
    style: Italic
  bold_italic:
    family: SFMono Nerd Font
    style: Bold Italic
  size: 14.0
window:
  opacity: 0.95
  # decorations: none
