accent: '#c0caf5'
background: '#1a1b26'
details: lighter
foreground: '#c0caf5'
terminal_colors:
  bright:
    black: '#414868'
    blue: '#7aa2f7'
    cyan: '#7dcfff'
    green: '#9ece6a'
    magenta: '#bb9af7'
    red: '#f7768e'
    white: '#c0caf5'
    yellow: '#e0af68'
  normal:
    black: '#16161e'
    blue: '#7aa2f7'
    cyan: '#7dcfff'
    green: '#9ece6a'
    magenta: '#bb9af7'
    red: '#f7768e'
    white: '#a8b1d6'
    yellow: '#e0af68'
