#!/usr/bin/env sh

# yabai scripting addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# bsp or float (default: float)
yabai -m config layout bsp

# New window spawns to the right or bottom of the current window
yabai -m config window_placement second_child

# Set all padding and gaps to 20pt (default: 0)
yabai -m config top_padding    8
yabai -m config bottom_padding 40
yabai -m config left_padding   8
yabai -m config right_padding  8
yabai -m config window_gap     8

# external bar settings
# yabai -m config external_bar all 100 100

yabai -m config window_zoom_persist on

# # on or off (default: off)
yabai -m config auto_balance off

# Floating point value between 0 and 1 (default: 0.5)
yabai -m config split_ratio 0.5

# set mouse to follow focus (default: off)
yabai -m config mouse_follows_focus off

# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier alt

# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autofocus

# space settings
yabai -m space 1 --layout float

# topmost settings
yabai -m config window_topmost off

# shadow settings
yabai -m config window_shadow float

# window opacity settings
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.95
yabai -m config window_opacity_duration 0.25

# window borders settings
yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config active_window_border_color 0xffB5B7B9
yabai -m config normal_window_border_color 0xff555555
yabai -m config window_animation_frame_rate  144
yabai -m config window_animation_duration     0
yabai -m config window_border_blur           off  
yabai -m config window_border_hidpi          on

# application rules
yabai -m rule --add app="^System Settings$" manage=off border=off opacity=1
yabai -m rule --add app="^Karabiner-Elements$" manage=off border=off opacity=1
yabai -m rule --add app="^Fantastical Helper$" manage=off border=off opacity=1
yabai -m rule --add app="^balenaEtcher$" manage=off border=off opacity=1
yabai -m rule --add app="^Spotify$" border=off opacity=1
yabai -m rule --add app="^Loopback$" manage=off border=off opacity=1
yabai -m rule --add app="^ColorSlurp$" manage=off border=off opacity=1
yabai -m rule --add app="^Poolsuite FM$" manage=off border=off opacity=1
yabai -m rule --add app="^CleanShot X$" manage=off border=off opacity=1
yabai -m rule --add app="^MacUpdater$" manage=off border=off opacity=1
yabai -m rule --add app="^Permute 3$" manage=off border=off opacity=1
yabai -m rule --add app="^Klokki$" manage=off border=off opacity=1
yabai -m rule --add app="^Arc$" opacity=1
yabai -m rule --add app="^Brave Browser$" opacity=1
yabai -m rule --add app="^Brave Browser$" title="^Picture in Picture$" border=off
yabai -m rule --add subrole="^AXDialog$" border=off manage=off
yabai -m rule --add subrole="^AXSystemDialog$" manage=off border=off
yabai -m rule --add app="^Telegram$" subrole="^AXUnknown$" border=off
yabai -m rule --add app="^Finder$" role="^AXWindow$" subrole="^AXDialog$" border=off
yabai -m rule --add app="^Finder$" title=".*Info.*" manage=off border=off
yabai -m rule --add app="^Velja$" manage=off border=off
yabai -m rule --add subrole="^Slack$" manage=on
yabai -m rule --add subrole="^AirBuddy 2$" manage=off border=off opacity=1
yabai -m rule --add subrole="^CleanShot X$" manage=off border=off opacity=1
yabai -m rule --add subrole="^ImageOptim$" manage=off border=off opacity=1
yabai -m rule --add subrole="^Numi$" manage=off border=off opacity=1
yabai -m rule --add subrole="^Lunar$" manage=off border=off opacity=1


# signals
# yabai -m signal --add event=window_destroyed action="fish -c 'destroyEmptySpaces'"